import assert from 'node:assert/strict';
import test from 'node:test';

import { evaluateEdgeFunctions, evaluateSupabaseConfig, hardenSupabaseConfig, parseToml } from './supabase-config-guard.mjs';

const secureConfig = `
[api]
max_rows = 1000

[storage]
file_size_limit = "10MiB"

[storage.buckets.avatars]
public = false
file_size_limit = "2MiB"
allowed_mime_types = ["image/png", "image/jpeg"]

[auth]
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["http://localhost:5173", "https://app.example.com/auth/callback"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
enable_anonymous_sign_ins = false
minimum_password_length = 10
password_requirements = "lower_upper_letters_digits"

[auth.rate_limit]
email_sent = 2
sign_in_sign_ups = 30
token_verifications = 30

[auth.email]
double_confirm_changes = true
enable_confirmations = true
secure_password_change = true

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[auth.external.google]
enabled = true
secret = "env(SUPABASE_AUTH_EXTERNAL_GOOGLE_SECRET)"

[functions.checkout]
verify_jwt = true
`;

test('parses sections, strings, numbers, booleans, arrays, and exception comments', () => {
  const parsed = parseToml('[a.b]\n# harness:allow public catalog\nx = "1" # trailing\ny = 2\nz = true\nw = ["a", "b"]\n');
  assert.equal(parsed.get('a.b.x').value, '1');
  assert.equal(parsed.get('a.b.y').value, 2);
  assert.equal(parsed.get('a.b.z').value, true);
  assert.deepEqual(parsed.get('a.b.w').value, ['a', 'b']);
  assert.equal(parsed.get('a.b.x').allowed, true);
  assert.equal(parsed.get('a.b.y').allowed, false);
});

test('accepts a hardened configuration', () => {
  assert.deepEqual(evaluateSupabaseConfig(secureConfig), []);
});

test('flags the weak defaults generated by supabase init', () => {
  const defaults = `[auth]\nsite_url = "http://127.0.0.1:3000"\njwt_expiry = 3600\nenable_refresh_token_rotation = true\nenable_anonymous_sign_ins = false\nminimum_password_length = 6\npassword_requirements = ""\n[auth.email]\ndouble_confirm_changes = true\nenable_confirmations = false\nsecure_password_change = false\n[auth.mfa.totp]\nenroll_enabled = false\nverify_enabled = false\n`;
  const problems = evaluateSupabaseConfig(defaults).join('\n');
  for (const expected of [/minimum_password_length/, /password_requirements/, /enable_confirmations/, /secure_password_change/, /mfa\.totp/]) assert.match(problems, expected);
});

test('flags risky auth, API, storage, and function settings unless an exception is written', () => {
  const risky = secureConfig
    .replace('enable_anonymous_sign_ins = false', 'enable_anonymous_sign_ins = true')
    .replace('jwt_expiry = 3600', 'jwt_expiry = 604800')
    .replace('"https://app.example.com/auth/callback"', '"https://*.example.com/**"')
    .replace('sign_in_sign_ups = 30', 'sign_in_sign_ups = 1000')
    .replace('max_rows = 1000', 'max_rows = 100000')
    .replace('file_size_limit = "10MiB"', 'file_size_limit = "5GiB"')
    .replace('public = false', 'public = true')
    .replace('verify_jwt = true', 'verify_jwt = false')
    .replace('"env(SUPABASE_AUTH_EXTERNAL_GOOGLE_SECRET)"', '"GOCSPX-literal-secret-value"');
  const problems = evaluateSupabaseConfig(risky).join('\n');
  for (const expected of [/enable_anonymous_sign_ins/, /jwt_expiry/, /curinga/, /sign_in_sign_ups/, /max_rows/, /file_size_limit/, /buckets\.avatars\.public/, /functions\.checkout\.verify_jwt/, /auth\.external\.google\.secret/]) {
    assert.match(problems, expected);
  }
  const excepted = risky.replace('public = true', '# harness:allow public product images\npublic = true');
  assert.doesNotMatch(evaluateSupabaseConfig(excepted).join('\n'), /buckets\.avatars\.public/);
});

test('requires size and type limits on every configured bucket', () => {
  const problems = evaluateSupabaseConfig('[storage.buckets.docs]\npublic = false\n').join('\n');
  assert.match(problems, /docs.*file_size_limit/);
  assert.match(problems, /docs.*allowed_mime_types/);
});

test('flags Edge Functions with open CORS or privileged keys and no caller check', () => {
  const files = {
    'supabase/functions/open/index.ts': "const headers = { 'Access-Control-Allow-Origin': '*' };",
    'supabase/functions/admin/index.ts': "const admin = createClient(url, Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);\nawait admin.from('x').delete();",
    'supabase/functions/safe/index.ts': "const admin = createClient(url, Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);\nconst { data } = await userClient.auth.getUser();",
    'supabase/functions/webhook/index.ts': "// harness:allow-cors public webhook verified by signature\nconst headers = { 'Access-Control-Allow-Origin': '*' };",
  };
  const problems = evaluateEdgeFunctions(files).join('\n');
  assert.match(problems, /open.*CORS/);
  assert.match(problems, /admin.*chave privilegiada/);
  assert.doesNotMatch(problems, /safe|webhook/);
});

test('hardens the supabase init defaults in place, keeping comments and other keys', () => {
  const defaults = `[auth]\n# Passwords shorter than this value will be rejected.\nminimum_password_length = 6\npassword_requirements = ""\njwt_expiry = 3600\n\n[auth.email]\ndouble_confirm_changes = true\nenable_confirmations = false\nsecure_password_change = false\n\n[auth.mfa.totp]\nenroll_enabled = false\nverify_enabled = false\n\n[auth.mfa.phone]\nenroll_enabled = false\n`;
  const hardened = hardenSupabaseConfig(defaults);
  assert.match(hardened, /# Passwords shorter/);
  assert.match(hardened, /minimum_password_length = 10/);
  assert.match(hardened, /\[auth\.mfa\.phone\]\nenroll_enabled = false/);
  assert.deepEqual(evaluateSupabaseConfig(hardened), []);
  assert.equal(hardenSupabaseConfig(hardened), hardened);
});

test('review: multi-line arrays, inline tables, and every secret-like key are checked', () => {
  const config = `[auth]\nsite_url = "http://127.0.0.1:3000"\nadditional_redirect_urls = [\n  "https://*.pages.dev/**",\n  "http://evil.example.com",\n]\n[auth.email.smtp]\npass = "literal-password"\n[edge_runtime.secrets]\nSTRIPE_KEY = "sk_test_literal"\n[studio]\nopenai_api_key = "literal-openai"\n[db.vault]\nsecret_key = "env(SECRET_VALUE)"\n[functions]\nhello = { verify_jwt = false }\n`;
  const problems = evaluateSupabaseConfig(config).join('\n');
  assert.match(problems, /curinga/);
  assert.match(problems, /não usa HTTPS/);
  assert.match(problems, /auth\.email\.smtp\.pass/);
  assert.match(problems, /edge_runtime\.secrets\.STRIPE_KEY/);
  assert.match(problems, /studio\.openai_api_key/);
  assert.doesNotMatch(problems, /db\.vault\.secret_key/);
  assert.match(problems, /functions\.hello.*tabela inline/);
});

test('review: --fix adds hardened keys missing from configs made by older CLIs', () => {
  const hardened = hardenSupabaseConfig('[auth]\nminimum_password_length = 6\n\n[auth.email]\nenable_confirmations = false\n');
  assert.deepEqual(evaluateSupabaseConfig(hardened), []);
});

test('review: shared function code is scanned and comments do not count as caller checks', () => {
  const files = {
    'supabase/functions/_shared/cors.ts': "export const corsHeaders = { 'Access-Control-Allow-Origin': '*' };",
    'supabase/functions/_shared/admin.ts': "export const admin = createClient(url, Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);",
    'supabase/functions/delete-user/index.ts': "import { admin } from '../_shared/admin.ts';\n// TODO: call auth.getUser( later\nawait admin.auth.admin.deleteUser(id);",
  };
  const problems = evaluateEdgeFunctions(files).join('\n');
  assert.match(problems, /_shared.*CORS/);
  assert.match(problems, /delete-user.*chave privilegiada/);
});
